spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com:
      ct08:
        PharmacyManagement: INFO
        com.p6spy: OFF # Không cho phép log p6spy in ra bất cứ thứ gì
        org.hibernate.SQL: OFF
        org.hibernate.type.descriptor.sql: OFF
        org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: OFF
decorator:
  datasource:
    p6spy:
      enable-logging: false # Tắt P6Spy hoàn toàn


